<?php
header('Content-Type: application/json');

// Allow only POST requests
if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    http_response_code(405);
    echo json_encode(['success' => false, 'message' => 'Method Not Allowed']);
    exit;
}

// Read raw JSON data sent by Fetch
$inputJSON = file_get_contents('php://input');
$input = json_decode($inputJSON, true);

if (!$input || !isset($input['image']) || !isset($input['ticker'])) {
    http_response_code(400);
    echo json_encode(['success' => false, 'message' => 'Bad Request: Missing image or ticker']);
    exit;
}

$ticker = preg_replace('/[^A-Za-z0-9]/', '', $input['ticker']); // Sanitize ticker name
$base64Image = $input['image'];

// Base64 generated by html2canvas comes in the format: data:image/png;base64,iVBOR...
if (strpos($base64Image, 'data:image/') === 0) {
    $parts = explode(',', $base64Image);
    if (count($parts) === 2) {
        $base64Image = $parts[1]; // Get only the base64 payload
    }
}

$decodedImage = base64_decode($base64Image);

if ($decodedImage === false) {
    http_response_code(400);
    echo json_encode(['success' => false, 'message' => 'Failed to decode Base64 image']);
    exit;
}

// Create destination folder if it doesn't exist
$saveDir = __DIR__ . '/../assets/graphs-png/';
if (!is_dir($saveDir)) {
    mkdir($saveDir, 0755, true);
}

// File name: PLT.png, POL.png, etc.
$fileName = strtoupper($ticker) . '.png';
$filePath = $saveDir . $fileName;

// Save the file
if (file_put_contents($filePath, $decodedImage)) {
    // Return relative path for the image
    $publicUrl = '/assets/graphs-png/' . $fileName;
    echo json_encode(['success' => true, 'url' => $publicUrl]);
} else {
    http_response_code(500);
    echo json_encode(['success' => false, 'message' => 'Failed to save image on server']);
}
?>
